### ISSUE TITLE
[1.13.0] 173 warnings

### ISSUE THREAD

**Issue by MaximeLM** [BatchLabs/ios-sdk#12]
Looks like #4 happened again:

`warning: (arm64) /Users/arnaud/dev/gitlab/batch-mobile/ios-sdk/sdk/build/Batch.build/Debug-iphoneos/Batch.build/Objects-normal/arm64/BALCachingContext.o unable to open object file: No such file or directory`

Using CocoaPods 1.5.3

**Comment by abarisain** [comment]
I'm not reproducing this successfully yet. Especially weird that this time, it mentions the Debug build.
Are you using Xcode 10 or 9?

We'll work on this and fix it ASAP.

**Comment by abarisain** [comment]
Found the issue: it looks like the build settings were incorrectly set at some point, and produced debugging symobls.

**Comment by abarisain** [comment]
I republished the built SDK (but didn't make a 1.13.1).

Could you try reinstalling the pod? I'm not sure whether cocoapods has a blob cache somewhere, but the newly extracted Batch binary should be 32 mb rather than 36.

**Comment by abarisain** [comment]
I have gotten feedback that the fix is working. Make sure you clear cocoapod's cache!

Please re-open the issue if you still have a problem.

**Comment by MaximeLM** [comment]
Hello, the problem happened again with v1.14.0 :

`warning: (arm64) /Users/arnaud/dev/gitlab/batch-mobile/ios-sdk/sdk/build/Batch.build/Debug-iphoneos/Batch.build/Objects-normal/arm64/BALCachingContext.o unable to open object file: No such file or directory`

**Comment by abarisain** [comment]
Thanks, we'll hotfix tomorrow.

**Comment by abarisain** [comment]
Tomorrow turned into "in the next half hour": the SDK has been rereleased. Once again, please make sure you clear cocoapod's cache.
