### ISSUE TITLE
Can't archive Batch 1.13.0 with swift 4.1 on Xcode 9.4

### ISSUE THREAD

**Issue by matvdg** [BatchLabs/ios-sdk#13]
We didn't migrate yet to Xcode 10 / Swift 4.2 and we can't archive anymore with the last version of Batch, I had to downgrade to 1.12.0.

It looks like a Bitcode version conflict : 
`ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1000.11.45.2_0' Reader: '902.0.39.1_0')', using libLTO version 'LLVM version 9.1.0, (clang-902.0.39.1)' for architecture armv7`

**Comment by abarisain** [comment]
Thanks for the report. I guess this could be worked around by disabling bitcode for your app, but that may not be desirable.

We'll edit the changelog to remove mention of Xcode 9 compatibility. This didn't surface in our tests, but I don't know if we went as far as archiving an Xcode 9 app with bitcode enabled.

**Comment by matvdg** [comment]
Yes, we read about bitcode, but it didn't fix the issue :-(

**Comment by abarisain** [comment]
I guess you could additionally strip the Bitcode from Batch's binary, but that's a lot of work for little gain.
