### ISSUE TITLE
promptForSystemNotificationConsent no member in Batch 1.13.0 with Xcode

### ISSUE THREAD

**Issue by muthukrishnanOCS** [BatchLabs/ios-sdk#14]
Hi,
i'm getting the error on given line in iOS SDK integration
`BatchPush.promptForSystemNotificationConsent()`
Type 'BatchPush' has no member 'promptForSystemNotificationConsent'
please let me know the solution

**Comment by abarisain** [comment]
Right, looks like a mistake slipped into the headers.

You should call "BatchPush.requestNotificationAuthorization()"
