### ISSUE TITLE
BUG IN CLIENT OF libsqlite3.dylib

### ISSUE THREAD

**Issue by nyeu** [BatchLabs/ios-sdk#16]
I am running Batch in my project for a while and I haven't seen any custom data coming into the dashboard. The native data comes correctly but not any of the custom ones.
I have been debugging it and all the events are called and they have the correct format, the only scary log I have seen so far is this one:

`[logging] BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /Users/joan/Library/Developer/CoreSimulator/Devices/496A40CA-E37C-4509-ACE2-3A0481A0B83E/data/Containers/Data/Application/C80A6067-E96B-480D-9B54-96FCE079152C/Library/Application Support/com.batch.ios/ba_tr.db`

Is this something to worry about?

**Comment by abarisain** [comment]
Closing this to clean up the issue tracker as we never managed to reproduce this.
If there is any evolution, feel free to re-open this ticket or hit us up on our support page.
