### ISSUE TITLE
BatchExtension.framework contains unsupported architectures '[x86_64, i386]'

### ISSUE THREAD

**Issue by mboudaoud** [BatchLabs/ios-sdk#17]
Hello,

We have been using the Batch iOS SDK for some time now, and we are having an issue when updating to the last version 1.13.2 (actually even with some earlier versions). We cannot publish our app to iTunes Connect due to this error: 'BatchExtension.framework contains unsupported architectures '[x86_64, i386]''.
We are using Xcode 9.4.1 along with CocoaPods.
Searching the web, we actually found out that it was due to some Simulator binaries included in the SDK, and that we could actually add a build phase script removing those binaries, but I don't think that this solution is sustainable.

**Comment by mboudaoud** [comment]
All right thank you for the support, i'm gonna add this script:
`APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
    FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
    FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
    echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

    EXTRACTED_ARCHS=()

    for ARCH in $ARCHS
    do
        echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
        lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
        EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
    done

    echo "Merging extracted architectures: ${ARCHS}"
    lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
    rm "${EXTRACTED_ARCHS[@]}"

    echo "Replacing original executable with thinned version"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done`

**Comment by abarisain** [comment]
While this should work, I suggest sticking with the script we provide.
