### ISSUE TITLE
Not working. No message in Xcode console

### ISSUE THREAD

**Issue by gazedash** [BatchLabs/ios-sdk#18]
I followed a guide but I can't see ```[Batch] Batch started with a DEV API key``` in console

Batch version: 1.13

 https://batch.com/doc/ios/sdk-integration/initial-setup.html

**Comment by abarisain** [comment]
Hello,

Please note that this message only appears for DEV API Keys, not LIVE ones.

You can reach us over https://batch.com/support for integration issues

**Comment by gazedash** [comment]
@abarisain I'm using DEV key, and it works fine with android sdk.
