### ISSUE TITLE
Include BatchExtension.framework in Carthage zip

### ISSUE THREAD

**Issue by MaximeLM** [BatchLabs/ios-sdk#21]
BatchExtension.framework could be included with each release in Batch.framework.zip.

Carthage supports bundling multiple frameworks : https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

This would allow Carthage users to link Batch.framework to their app target and BatchExtension.framework to their extension target. BatchExtension.framework would have to be included in the `carthage copy-frameworks` build phase.

**Comment by abarisain** [comment]
Hello,

Thanks for your feedback.

The plan is actually to migrate to an open-source swift rewrite of the extension.
It's a work in progress, so it's not publically documented yet, but it is installable with swiftPM and Carthage should probably work automatically. Carthage is missing for now.

You can find it here: https://github.com/BatchLabs/Batch-iOS-SDK-Extension
