### ISSUE TITLE
1.15.1 incompatible with xcode 11.3.1 (Mojave last version)

### ISSUE THREAD

**Issue by benoitvallon** [BatchLabs/ios-sdk#23]
1.15.1  has been compiled with xcode 11.5 which makes it incompatible with older versions of xcode like xcode 11.3.1 the last xcode version available with Mac OS Mojave.

The error is like that : 

```
Invalid bitcode version (Producer: '1103.0.32.62.0_0' Reader: '1100.0.33.17_0') ...
```

The only way to resolve it is to disable the bitcode option but it is not something recommended. Could you provide another build and pod, please ? Thanks

**Comment by gouyelliot** [comment]
Hello,

This is intended, and is mentioned in our [changelog](https://github.com/BatchLabs/ios-sdk/blob/master/SDK/CHANGELOG.md). If you must stay on Xcode 11.3, you should use Batch SDK v1.15.0.

**Comment by benoitvallon** [comment]
This is what I did.

But is there anything in the new build that requires the compilation with xcode 11.5 ? The Changelog mentioned nothing specific to xcode 11.5 that's why I posted the issue.

**Comment by abarisain** [comment]
Hi,

It's an internal policy of ours to compile Batch with the latest Xcode available. Even if that's not the case here, we often add internal changes that may need conditional code for major and minor versions, which requires the latest SDK to build.

We only use older Xcode versions when we really need to ship an important fix: the changes in 1.15.1 don't really justify this.

Unfortunately, bitcode is quite hostile to binary frameworks. Apple doesn't always break compatibility with Xcode versions, but often does.

**Comment by abarisain** [comment]
1.15.1 is probably the last 1.15.x version, so if you don't need the changes we mentionned, I suggest you lock to 1.15.0

**Comment by benoitvallon** [comment]
This would have been another reason to wait for 1.16.0 to make that move. A patch version change isn't supposed to break the compatibility.
