### ISSUE TITLE
Support for iOS7?

### ISSUE THREAD

**Issue by geek-paulwong** [BatchLabs/ios-sdk#3]
I realize that the SDK via Cocoapods only supports iOS8+. Is manual installation the way to support iOS7? And does the SDK itself go compatible with iOS7? Thank you!

**Comment by guenard** [comment]
Hello @geek-paulwong, **we removed iOS 7 support [in Batch iOS SDK 1.6](https://batch.com/doc/ios/advanced/sdk-changelog.html)** as iOS 8 is now the minimum deployment version for Xcode 8.

You can still implement Batch 1.5.4 via Cocoapods or direct integration as it still supports iOS 7:
`pod 'Batch', '1.5.4'`

**Comment by geek-paulwong** [comment]
I checked out top 10 apps and found out that they all started supporting only iOS8+ quite a while ago.  So I will stick to iOS8+ from now on, as well! Thanks for letting me know, @guenard !

**Comment by guenard** [comment]
You are welcome @geek-paulwong ;) Please let us know if you need any help, we have a cool live chat feature on our web dashboard.
