### ISSUE TITLE
144 warnings

### ISSUE THREAD

**Issue by geek-paulwong** [BatchLabs/ios-sdk#4]
warning: (arm64) /Users/arnaud/dev/gitlab/batch-mobile/ios-sdk/sdk/build/batch.build/Release-iphoneos/Batch.build/Objects-normal/arm64/NSObject+BASwizzled.o unable to open object file: No such file or directory

and etc...

I guess the package is somehow archived with redundant incorrect paths? Does not affect the SDK functionalities tho.

Batch v1.7.0

**Comment by abarisain** [comment]
Thanks, we'll look into it.

Does your Podfile have "use_frameworks!"?

**Comment by abarisain** [comment]
I can't seem to reproduce this. Can you please check if this is the issue that affects you? https://github.com/CocoaPods/CocoaPods/issues/4237

**Comment by geek-paulwong** [comment]
@abarisain Thanks for the links, it looks like Cocoapods' own problems. I downgraded to Batch 1.6.0 and no more such warnings appear anymore. Thank you!

**Comment by abarisain** [comment]
This issue has been fixed since in the 1.7.1 release, which will be out in a couple of hours.

**Comment by geek-paulwong** [comment]
@abarisain thank you!
