### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by sebastian-julius** [BatchLabs/ios-sdk#7]
What License is this sdk running at? We're doing an internal audit of licenses and wondered what it was for the sdk.

It'd be great if you could add a LICENSE file and describe it.

**Comment by abarisain** [comment]
Hi!

The sample code is under the MIT, but the SDK is simply under our copyright, as it is a closed source binary.

A LICENSE file is lacking, but I'm not sure on how to correctly make one per sample.

**Comment by sebastian-julius** [comment]
Okay, I see. Good question how to distinguish them as they're within one repository. Maybe you can separate the sdk and the examples into two different repos and put a LICENSE file into the sdk like Newrelic does https://github.com/newrelic/rpm/blob/master/LICENSE? The examples could be MIT then. Just an idea. If you don't like that, just close this issue. No sweat

**Comment by abarisain** [comment]
Hello,

The latest commit, as of writing, adds LICENSE files in the repo root, and "Sample Projects" folder.
