### ISSUE TITLE
"com.batch" key usage in push notification payload

### ISSUE THREAD

**Issue by Droppix** [BatchLabs/ios-sdk#8]
Hi,

When I received a notification, in my json, I have 3 parameters :

- i = yyyyy
- od = { n = "xxxxx" }
- t = c

`{
    aps :{
        alert:{
            body : test
            title :test
        }
        "content-available" :1
        "mutable-content" :1
    };
    "com.batch" =     {
        i : 2933064,
        od : {
            n :"6a16e6f0-f564-11e7-9328-c954f5a3287f"
        },
        t :c
    },
}`
What are their uses? (I didn't find anything in the documentation)

Thanks;

**Comment by abarisain** [comment]
Hi,

Keys under "com.batch" are considered private, and are used by the SDK to provide features such as automatic deeplink handling, open rate tracking and mich more.

**Comment by Droppix** [comment]
Can I consider that "i" has a unique value? (I need unique identifier of campaign -> long and not uuid)

**Comment by abarisain** [comment]
Sorry, but we don't make any promise about what "com.batch" contains at this time, or what will change in the future.  

In your case "i" might not always be unique or even be present at all. If you want to add a unique identifier to your campaigns, please use the custom payload feature.

**Comment by Droppix** [comment]
Ok, but it's a big problem.
The people who will use the dashboard, are supposed to be "marketers" and not "techs", and I cannot ask them to generate "a unique identifier" in the payload:(

**Comment by abarisain** [comment]
Until we natively add tracking support, you can add a macro to your custom payload. There is one for the campaign identifier:

<img width="476" alt="screen shot 2018-01-10 at 10 33 06" src="https://user-images.githubusercontent.com/312529/34765396-a96d8704-f5f1-11e7-8553-718befaa7e6d.png">


Note that it will not be a long, but a string, and should not be used to sort the received notifications.

What's use are you trying to make of this unique identifier? Analytics?

**Comment by Droppix** [comment]
En français;)

Sans rentrer trop dans le détail technique, j'ai une base de donnée locale, qui stock tous les messages reçus (des notifs simple, et des commandes interne relativement complexe qui doivent être soumis en mode "silent"). Cette base nous sert entre autre à afficher la plupart des notifications (Inbox), et bien sûre, l'identifiant unique sert à éviter les doublons dans la base (car cela arrive, notamment au mode silent).

**Comment by guenard** [comment]
@Droppix Batch propose déjà une fonctionnalité [Inbox](https://batch.com/doc/ios/inbox.html). Si vous ne souhaitez pas l'utiliser, vous pouvez remonter l'ID de campagne dans le payload comme précisé ci-avant par @abarisain. Mais nous n'exposons pas officiellement d'ID unique de notification côté SDK à moins de détourner `com.batch` (ce que nous déconseillons évidemment). Pour toute autre question spécifique à votre usage, je vous invite à nous écrire sur [support@batch.com](mailto:support@batch.com) ou utiliser notre live chat.
